# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#   workflow_dispatch:

# jobs:

#   CI:

#     runs-on: ubuntu-latest

#     steps:
#     - name: checkout code
#       uses: actions/checkout@v3
      
#     - name: Build the Docker image
#       run: |
#         docker build . --file Dockerfile --tag oreldiei/workflow:latest
#         docker tag oreldiei/workflow:latest oreldiei/workflow:${{ github.run_number }}-${{ github.sha }}
        
#     - name: login to docker hub
#       run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
  
#     - name: push docker image to reg
#       run: docker push oreldiei/workflow:${{ github.run_number }}-${{ github.sha}} && docker push oreldiei/workflow:latest
